project:
  type: default
  output-dir: _book
  render:
    - index.qmd


bibliography:
- references.bib

format:
  html:
    theme: [cosmo, farness-theme.scss]
    toc: false
    number-sections: false
    favicon: /favicon.svg

repo-url: https://github.com/MaxGhenis/farness
license: MIT
